travis:
  secure:
    BINSTAR_TOKEN: rVYWcJkVZOzKbll1ZXgRE8OaHQhotbSvy6SzvyIH1G90qDv8BRfL40yLJAR3uM0Fi0sCHfk5OaDSKFeaUEnbMDNmoZCSgzonkBN2K7Mx4i/bdJB+S/4PVxLL29GLJwY1wFA54cKRrzDuFW9h6xZBpsi6woOe/YNfcTxJ2PlXzrPNT8eyYyGd+xiPKh8ySvREJjkpK68ECgjH4soqGAY8e6I39S5sEpDRFjPe5+ZbOBYJVi8HyqTQNBss1sfwzZ61uaqoFSL2qjqiitVmQvSLYNBTEVESQUqJo2oHxp2tPIoqViWeuB/i4nz7RqbYqgwLZUVeKBl8143enTgaB+jKur9eq74XDFXw5pzHhOhwA4TyxYSpI3Na+AKpnAge1kGHRynSXmzAKiQ1ZquaTlQE+WcBtC8pH9c1x8eP4B3bKrtUTnXkMo2S8rERruU94AZ06M3yRZd7Df8lYaFcoQca9QQUs0+xKd45Dk2E7GHDhbX7hQWMZ3hNspdNbP0cKu41KsUAvL9HtUPyFnKcVgZCbW1je8twdi5KD7v1IJozzG7Pf78OeBxkSQJX8ZCkqSSITSFUACSUcDytdDbjizD5R2at+yb6/E0EiuxBY8EXUFFe1lxpSRK7AqF4PL8IoVlQwMGeIhUcthCGWNZqgyrZnO9zJQgemnLQPDMtXy3in+M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
