travis:
  secure:
    BINSTAR_TOKEN: WqRxeevQZaunIThxo/nM5u/GmaABzao17ddMxTy8jQzFCIiOxpcbomGCW7SdBq7h8xVMr/dcjLjHir0hGs1xXSWJBsEjwLwbwZAjyD6LZtWnOdTQP3CfDeWLxUufT7Exkz3sqkaVfii9wSyOPMNPDexAYsvxUEKKZIusZPe5iX8h17KXm7vkEPhvN+ynTvDQQzW6gMKjHQjKWffZ30AWct8h3qR1dBvnuc5RULNwQCC8/V3dYF1bouME9/NDgvVl3ITgojlsWAed99eFY9DlG39kFtM/X7VdTiVC4NM/6sq59gzHhCeyMMBk1fVIsAO64PV9Tv1xnTRWesZXxr1NUYaOIRtlKzXBJFsXOWbKWfBopwDSRQxeczQw7wAkxm8rt/c2yWa9g5BlqEpPpq92vqj97BqydW1vXpafSaDBQqVnWPGyEgQJmR1cSHYr3L7SZcP5AV7+nfPt+NvPlEMbKaZwK+3ylSvn5pakUHNFNJK3hOd/Ikokd6YInMSnvyzuRBcHL6guwETt0rWu7RJrKzdsEufpyCDmfWt15KNhNv88ktOvnuOSHeQk6DVAj/PIav/RcNYObBC9I1gZYUsC7Wdcxr7MwXHdz1xyYYrHeINrP9AVxxpfr5kYBVDpQh4+sHdXcsysY4tcjEzz9u4VghWJCG72PUn2j7wXeOpTlLw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
