travis:
  secure:
    BINSTAR_TOKEN: osMrqrSF+fkYpWkj3QXIK41IQ+GOSxrpXoGXjMAXjzH8MlPdqjhHPxPTlrB4IU1UyVXb0Vcp74G7BGgdg0B/I2GXrY4SXGTV6NzZ4GzlgLP9+Jq5NcuGfKhybFJanRMcTkuY2enhdP3sf+/XyWU/6lCen1G1JWNiS11aICbQ+fS0jU27MaSkw3btyVAskhN5ADFfScCPACxFfkIhA/Khx8S/jZlKw0tlK/Nax1GQhcKIZEjKUXZRGiiJeOCYx60yaQmZzksyLzMtw5aG4r2ZOCG9BSqXcTDt6WlYJyaC8xMPCLsArjFPh0bDacqmbmK0OAymQhpwLs57YgIZTyvM8LLrxjqpXwIIU8wnR8gz4+EzFJWnrUXmxWOb8mVRH3oBNn8zZmgqFcrRl9jbL9u6vDlg6VzHtO+j3PTwEbGtluyOA8fet35qQYxCL1I6LLh93FBPN8M+RVrhcorgTKWUp0frY93FryquE1+3VA5WAg2BuAYhKCkK0Mrw3W3y3Rmo6/qS2nBcge83n8py56dcCCGOvYpOQ+9jt1HVK4FnJbLebJ7duBGiZ+0F3zb1qrb3nXmkdRur8t+e+30zTaKd8Q3t94SJ+kz4NEqKvO7Ri0VhNE97ADfNaZuSXozZZZiSMbuVnT/E1nkpy57O8Mj54fIZYlpcNY4fgtd6XkewlmM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
