travis:
  secure:
    BINSTAR_TOKEN: d/eUBTfK59QcnwxSNohKvJIexJMloRG/2f7OjdcMJpI1lPDdRe/Fo7jeTK2BQyNxN4+FG4JalxNqH00tId0+92ePL6JrY5L/49efvoUXFIpwEwoQtxd3yHev1qT2SBdY/D1PlX/mD9KGc+6Z+KnF4YuEmdQMk3lb7vUP7ShrgNElC6FgUm2p8x/IDgglpldZacxJ3e4k6oq2xE5qyi1PsQFUAWysqq4vCE02NPxUUJYvfCnHY2gv302ju91omDdd215riMfuAgFIta20luk7Jhqb90CkTWgj/j2dvi7yw5fh6yZRVWxpGCNmlUjICAUEmaXR5TK0mmBeic0yAXpzvCBhYowhzp16luScgTgwQndvUBScmzNrABEZpeww7RG1tbMT53MGEiY9bX4Xr2PkzqDh3T5b5Yw07XWiVcCGqAoTal1gj+uF2qyc2DbJs8rGIqILOn4fGZfMoEYD8Mtj7ptw9NznRX8rRu2OzUfButvVxDhE/E6PuO6iIYiC8W3hudf0UdlxgtMUaa1Qzbi4/Sr3C1ODS6RazhSD86jNVFAuIZsaQw3JeqPwkwi3eSUq/sepvy7diQCRsxLtlLsWT2CZLas0fPZ0AZq99JLeNdOJBzsvAEidw8PzHN3lxoWSB+zIN+ihAl8fupsbC2FqopO7Gk8rc+XW5vTm5Nqahls=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
